### PR TITLE
update gems

### PR DESCRIPTION
**Pull request by laudickson**
updating gemfile

### CODE REVIEW

**Comment by laudickson** [comment]
@jscho13 @K9Advantix53 one of you take a look at these changes and then comment back if its ready to merge or whatever feedback

**Comment by jscho13** [comment]
No uglifier and turbolinks? I thought those were kinda useful

**Comment by greysteil** [comment]
If you re-run the bundle update now you'll get Rails 5.1.4, rather than the release candidate version 🎉 .

**Comment by laudickson** [comment]
Thanks for the heads up @greysteil! I was actually hitting this really annoying activesupport dependency bug relating to the pre-release.

@jscho13 - haven't really used uglifier or turbolinks since Launch (even then I didn't understand it) - I'll add them back in.

**Comment by greysteil** [comment]
No worries - I spend more time than I should cruising through dependency update PRs looking for people who might benefit from using Dependabot, so it's nice to be able to help out here and there while I do. 😄

**Pull request merged**
